"""
hypothesis_gen.py — Generate new strategy variants for the brain to test.

Two bands of aggressiveness:

SAFE BAND — small perturbations around the current best-known config.
  Examples: long_threshold ±0.25, K_SL ±0.25, STABILITY_N ±1, timeframe held.
  Purpose: local search, gradient-descent-like refinement.

AGGRESSIVE BAND — wide combinatorial sweep + structural variants.
  Examples: switch timeframe, swap filters on/off, change label_period, try
  label scheme variants (return vs delta vs barrier).
  Purpose: discover non-local optima the safe band can't reach.

Both bands run in parallel — the brain isn't supposed to choose between them.
"""
from __future__ import annotations

import itertools
import json
import random
from pathlib import Path
from typing import Any

from experiment_log import queue_hypothesis, read_log, best_by_metric

# ──────────────────────────────────────────────────────────────────────────
# Architecture flags (2026-05-19): live bot moved to v23. v22 code kept on
# disk for history (same pattern as AiGuardrailStrategy / FinBuddyLLMModel)
# but no longer generated by the brain. Flip this flag back to True if you
# ever want parallel exploration again.
# ──────────────────────────────────────────────────────────────────────────
V22_ENABLED = False

# Analyst blacklist source — written every 6 h by scripts/brain/analyst.py
ANALYST_REPORT_PATH = Path(
    "/home/ubuntu/var/www/html/trade/finbuddy_memory/experiments/analyst_report.json"
)

# Data-coverage guard: skip a timeframe in random generation if its BTC
# feather file doesn't extend far enough to cover the active backtest windows.
DATA_DIR = Path("/home/ubuntu/var/www/html/trade/freqtrade/user_data/data/binance/futures")


def _load_analyst_blacklist() -> set[str]:
    """Return set of timeframes the analyst has flagged as dead/noisy.

    Falls through silently if the report doesn't exist yet (first runs).
    """
    try:
        data = json.loads(ANALYST_REPORT_PATH.read_text())
        findings = data.get("findings", {}) or {}
        return set(findings.get("dead_timeframes", [])) | set(findings.get("noisy_timeframes", []))
    except Exception:
        return set()


def _has_data_coverage(timeframe: str) -> bool:
    """Skip the timeframe if BTC's feather doesn't cover the backtest cutoff."""
    btc_file = DATA_DIR / f"BTC_USDT_USDT-{timeframe}-futures.feather"
    if not btc_file.exists():
        return False
    try:
        import pandas as pd
        df = pd.read_feather(btc_file)
        date_col = "date" if "date" in df.columns else df.columns[0]
        return str(df[date_col].max()) >= DATA_COVERAGE_CUTOFF
    except Exception:
        return False


def _available_timeframes(candidates: list[str]) -> list[str]:
    """Filter candidates by analyst blacklist + data coverage."""
    blacklist = _load_analyst_blacklist()
    return [tf for tf in candidates if tf not in blacklist and _has_data_coverage(tf)]


# ── Windows the brain evaluates on (3-month each, finish in <65min per runner) ──
# Mix of regimes for diversified evaluation. Each backtest must fit within the
# runner's 65-min lock window (BACKTEST_TIMEOUT_S=3900).
# NOTE (2026-05-22): added recent windows — prior windows only covered through
# 2025-04, missing 13 months of live market. Brain must evaluate on conditions
# it's actually deployed in.
# IMPORTANT: promote.py classifies windows by "bull"/"bear" substring in the
# window name. ALL window names here must include either "bull" or "bear" so
# they are correctly counted in the promotion gate logic.
# NOTE (2026-05-22): ALL prior experiments (268) used the old raw-% return target.
# Z-scored target added 2026-05-22. Old results have incompatible label distribution.
# New experiments carry target_version="zscore"; promote.py filters to zscore only.
DATA_COVERAGE_CUTOFF = "2026-01-01"  # ensure all windows have coverage
WINDOWS = {
    "bull_2024Q1": "20240101-20240401",   # BTC +60% — strong bull early-2024
    "bull_2024Q2": "20240401-20240701",   # mid-2024 chop/consolidation
    "bear_2025Q1": "20250101-20250401",   # BTC -28% — bear leg Q1 2025
    "bull_2025Q4": "20251001-20260101",   # BTC recovery Oct-Dec 2025 (renamed from recent_2025Q4)
    "bear_2026Q1": "20260101-20260401",   # BTC declining Jan-Apr 2026 (renamed from recent_2026Q1)
}

# Window order for queue generation: bull→bear pairs so the runner tests
# each config on one bull AND one bear back-to-back (~3h to both results).
# bull_2024Q2 first (historically strongest bull signal), bear_2025Q1 second
# (best WR/PF on bear), bear_2026Q1 at position 4 (promotion gate window),
# bull_2024Q1 last (hardest bull, least informative for initial validation).
PAIRED_WINDOWS = [
    "bull_2024Q2",
    "bear_2025Q1",
    "bull_2025Q4",
    "bear_2026Q1",
    "bull_2024Q1",
]

# Target version tag — added to every new queued experiment so promote.py can
# exclude the 268 legacy raw-% experiments (which have no target_version field).
TARGET_VERSION = "zscore"

# ══════════════════════════════════════════════════════════════════════════
# Two architectures live in the brain. Each has its own seed + param space.
# Brain explores BOTH in parallel — vision says broader perspective wins.
# ══════════════════════════════════════════════════════════════════════════

# v23 Regression — LightGBMRegressor predicting future_return %
SEED_CONFIG_V23 = {
    "arch":               "v23",
    "strategy":           "FinBuddyFreqAI_v23",
    "freqaimodel":        "LightGBMRegressor",
    "config_file":        "v23_regression_15m_di_config.json",
    "timeframe":          "15m",
    "long_threshold":     1.5,    # was 3.0 — z-scored N(0,1) predictions: ±3.0 hits 0.27% of candles
    "short_threshold":    -0.8,   # was -1.5 — tighter SHORT bar guides brain to explore better SHORT WR (2026-05-23)
    "k_sl":               2.0,
    "k_tp":               2.0,
    "stability_n":        2,
    "label_period_candles": 12,
    "filter_di":          True,
    "filter_svm":         True,
    "feature_set":        "all",   # which external features to include (see strategy FREQAI_FEATURE_SET)
    "n_estimators":       100,     # stamped so A/B comparisons are possible in experiment logs
}

# v22 Classifier+LLM — RETIRED 2026-05-19. v23 regression is live. V22_ENABLED=False keeps this dead.
# Kept for historical reference only. Do not re-enable without verifying brain config + windows.
SEED_CONFIG_V22 = {
    "arch":               "v22",
    "strategy":           "FinBuddyFreqAI",
    "freqaimodel":        "LightGBMClassifier",   # pure backtest; live wraps with LLM
    "config_file":        "v22_backtest_config.json",
    "timeframe":          "5m",
    "k_tp":               2.0,
    "k_sl":               1.0,
    "ml_threshold":       0.60,
    "label_period_candles": 72,
}

# Back-compat alias
SEED_CONFIG = SEED_CONFIG_V23


# ── SAFE BAND (architecture-aware) ────────────────────────────────────────

# Per-architecture perturbation menus. Each tuple: (param, delta, rationale).
PERTURB_V23 = [
    ("long_threshold",      +0.25, "tighter long entries"),
    ("long_threshold",      -0.25, "looser long entries"),
    ("short_threshold",     -0.25, "tighter short entries"),
    ("short_threshold",     +0.25, "looser short entries"),
    ("k_sl",                +0.25, "wider stop"),
    ("k_sl",                -0.25, "tighter stop"),
    ("k_tp",                +0.25, "more upside on trail"),
    ("k_tp",                -0.25, "tighter trail lock"),
    ("stability_n",         +1,    "stricter signal stability"),
    ("stability_n",         -1,    "looser signal stability"),
]

PERTURB_V22 = [
    ("k_tp",                +0.25, "wider take-profit"),
    ("k_tp",                -0.25, "tighter take-profit"),
    ("k_sl",                +0.20, "wider stop"),
    ("k_sl",                -0.20, "tighter stop"),
    ("ml_threshold",        +0.05, "tighter classifier threshold"),
    ("ml_threshold",        -0.05, "looser classifier threshold"),
]


def _clamp(v: dict, param: str) -> dict:
    """Clamp a perturbed param to a sane range."""
    if "threshold" == param.split("_")[-1] and param != "ml_threshold":
        if param == "short_threshold":
            v[param] = max(-3.0, min(-0.25, v[param]))   # was -6.0; z-score ±3σ is extreme enough
        else:
            v[param] = max(0.25, min(3.0, v[param]))     # was 6.0; ±3.0 already covers tail
    elif param == "ml_threshold":
        v[param] = max(0.45, min(0.85, v[param]))
    elif param.startswith("k_"):
        v[param] = max(0.5, min(4.0, v[param]))
    elif param == "stability_n":
        # Bug 4 fix (2026-05-30): clamp to [1, 4]. stability_n=-1 was being
        # queued (perturbation -1 from base=1), which the strategy silently
        # corrects to 1 via max(1,n) — but the config_hash stores -1, causing
        # confusion in logs and any future promotion. Min=1 is the valid floor.
        v[param] = max(1, min(4, int(v[param])))
    return v


def generate_safe_band(seed: dict | None = None, n: int = 8) -> list[dict]:
    """Small perturbations around the current best config — for the SAME architecture."""
    base = dict(seed or _current_best_config() or SEED_CONFIG_V23)
    # Older log entries don't have 'arch' — infer from strategy name
    if "arch" not in base:
        base["arch"] = "v22" if base.get("strategy") == "FinBuddyFreqAI" else "v23"
    perturbations = PERTURB_V22 if base["arch"] == "v22" else PERTURB_V23

    random.shuffle(perturbations)
    out = []
    for (param, delta, rationale) in perturbations[:n]:
        v = dict(base)
        if param not in v:
            continue
        if isinstance(v[param], int):
            v[param] = max(1, int(v[param] + delta))
        else:
            v[param] = round(float(v[param]) + float(delta), 3)
            v = _clamp(v, param)
        if v == base:
            continue
        out.append({
            "band": "safe",
            "rationale": f"safe [{base['arch']}]: {param} {'+' if delta>=0 else ''}{delta} ({rationale})",
            "config": v,
        })
    return out


def generate_safe_band_both(n_per_arch: int = 4) -> list[dict]:
    """SAFE band for active architectures (v22 skipped when V22_ENABLED=False).

    Seed each architecture from its own current-best. Disabled arches are
    silently skipped — same pattern as N8N pipeline retirement: code stays,
    flag flips off.
    """
    arch_seeds = [SEED_CONFIG_V23]
    if V22_ENABLED:
        arch_seeds.insert(0, SEED_CONFIG_V22)
    out = []
    for arch_seed in arch_seeds:
        best = _current_best_config_for_arch(arch_seed["arch"]) or arch_seed
        out += generate_safe_band(seed=best, n=n_per_arch)
    return out


# ── AGGRESSIVE BAND (architecture-aware) ──────────────────────────────────

AGGRESSIVE_CHOICES_V23 = {
    "timeframe":          ["5m", "15m", "30m", "1h", "4h"],
    "long_threshold":     [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 4.0],
    "short_threshold":    [-0.5, -1.0, -1.5, -2.0, -2.5, -3.0, -4.0],
    "k_sl":               [1.0, 1.5, 2.0, 2.5, 3.0],
    "k_tp":               [1.5, 2.0, 2.5, 3.0],
    "stability_n":        [1, 2, 3, 4],
    "label_period_candles": [12, 24, 48, 72, 144],
    "filter_di":          [True, False],
    "filter_svm":         [True, False],
    "feature_set":        ["all", "no_regime"],
    # LightGBM tree hyperparameters — previously locked, now swept by brain
    # Lower num_leaves = more regularized (less overfit); lower lr = better generalisation
    "num_leaves":         [15, 31, 63, 127],
    "learning_rate":      [0.01, 0.03, 0.05],
}

AGGRESSIVE_CHOICES_V22 = {
    "timeframe":          ["5m", "15m", "30m", "1h"],     # 4h underperforms v22-style classifier
    "k_tp":               [1.5, 2.0, 2.5, 3.0],
    "k_sl":               [0.8, 1.0, 1.2, 1.5, 2.0],
    "ml_threshold":       [0.55, 0.60, 0.65, 0.70, 0.75],
    "label_period_candles": [6, 12, 24, 48, 72],
}

# Timeframe → config file map (per architecture)
TF_CONFIG_MAP_V23 = {
    "5m":  "backtest_config.json",
    "15m": "v23_regression_15m_di_config.json",
    "30m": "v23_regression_30m_config.json",
    "1h":  "v23_regression_1h_config.json",
    "4h":  "v23_regression_4h_config.json",
}

TF_CONFIG_MAP_V22 = {
    # All v22 variants share v22_backtest_config.json but override timeframe via env.
    # FreqTrade respects --timeframe CLI arg over config's timeframe.
    "5m":  "v22_backtest_config.json",
    "15m": "v22_backtest_config.json",
    "30m": "v22_backtest_config.json",
    "1h":  "v22_backtest_config.json",
}


def _generate_aggressive_v23(n: int) -> list[dict]:
    # Filter the timeframe pool by analyst blacklist + actual data coverage.
    allowed_tfs = _available_timeframes(AGGRESSIVE_CHOICES_V23["timeframe"])
    if not allowed_tfs:
        # No timeframe survives gating — fall back to the seed default so the
        # brain keeps making progress instead of generating zero hypotheses.
        allowed_tfs = [SEED_CONFIG_V23["timeframe"]]
    out, seen = [], set()
    attempts = 0
    while len(out) < n and attempts < n * 5:
        attempts += 1
        v = {k: random.choice(c) for k, c in AGGRESSIVE_CHOICES_V23.items()}
        v["timeframe"] = random.choice(allowed_tfs)
        v["short_threshold"] = -abs(v["short_threshold"])
        v["arch"] = "v23"
        v["strategy"]    = "FinBuddyFreqAI_v23"
        v["freqaimodel"] = "LightGBMRegressor"
        v["config_file"] = TF_CONFIG_MAP_V23[v["timeframe"]]
        key = tuple(sorted(v.items()))
        if key in seen:
            continue
        seen.add(key)
        rationale = (
            f"aggr [v23]: tf={v['timeframe']} lt={v['long_threshold']:+} st={v['short_threshold']:+} "
            f"ksl={v['k_sl']} ktp={v['k_tp']} N={v['stability_n']} lp={v['label_period_candles']} "
            f"di={v['filter_di']} svm={v['filter_svm']} feat={v.get('feature_set','all')}"
        )
        out.append({"band": "aggressive", "rationale": rationale, "config": v})
    return out


def _generate_aggressive_v22(n: int) -> list[dict]:
    out, seen = [], set()
    attempts = 0
    while len(out) < n and attempts < n * 5:
        attempts += 1
        v = {k: random.choice(c) for k, c in AGGRESSIVE_CHOICES_V22.items()}
        v["arch"] = "v22"
        v["strategy"]    = "FinBuddyFreqAI"
        v["freqaimodel"] = "LightGBMClassifier"
        v["config_file"] = TF_CONFIG_MAP_V22[v["timeframe"]]
        key = tuple(sorted(v.items()))
        if key in seen:
            continue
        seen.add(key)
        rationale = (
            f"aggr [v22]: tf={v['timeframe']} ktp={v['k_tp']} ksl={v['k_sl']} "
            f"thr={v['ml_threshold']} lp={v['label_period_candles']}"
        )
        out.append({"band": "aggressive", "rationale": rationale, "config": v})
    return out


def _top_k_results(k: int = 3, min_trades: int = 20) -> list[dict]:
    """Return top-K zscore experiments by profit_pct (filtered by min trade count).

    Restricted to target_version='zscore' only — the 268 legacy raw-% experiments
    have incompatible label distributions and must not seed guided exploration.
    """
    log = [r for r in read_log()
           if r.get("status") == "completed"
           and r.get("config", {}).get("target_version") == "zscore"
           and r.get("metrics", {}).get("trades", 0) >= min_trades]
    if not log:
        return []
    log.sort(key=lambda r: r["metrics"].get("profit_pct", -1e9), reverse=True)
    return log[:k]


def _generate_guided_aggressive(n: int) -> list[dict]:
    """
    Guided exploration — pick top-K from experiment log and generate medium
    perturbations around each (between safe-band ±0.25 and aggressive random).
    Focuses compute on promising regions instead of pure-random sweep.
    """
    top = _top_k_results(k=3)
    if not top:
        return []  # no signal yet — caller falls back to pure-random aggressive
    out = []
    attempts = 0
    while len(out) < n and attempts < n * 8:
        attempts += 1
        parent = random.choice(top)
        base = dict(parent["config"])
        arch = base.get("arch") or ("v22" if base.get("strategy") == "FinBuddyFreqAI" else "v23")
        choices = AGGRESSIVE_CHOICES_V22 if arch == "v22" else AGGRESSIVE_CHOICES_V23
        # Mutate 2 random dimensions with medium step (one notch in the choice list)
        v = dict(base)
        for param in random.sample(list(choices.keys()), k=min(2, len(choices))):
            opts = choices[param]
            if v.get(param) in opts:
                idx = opts.index(v[param])
                step = random.choice([-1, 1])
                v[param] = opts[max(0, min(len(opts) - 1, idx + step))]
            else:
                v[param] = random.choice(opts)
        if arch == "v23":
            v["short_threshold"] = -abs(v["short_threshold"])
            # Drop guided mutations that land on a dead/blacklisted timeframe.
            # _generate_aggressive_v23 already filters via _available_timeframes(),
            # but guided exploration mutates params one-by-one and can step from
            # '15m' into '5m' or '30m' which the analyst has flagged as dead.
            allowed_tfs = _available_timeframes(AGGRESSIVE_CHOICES_V23["timeframe"])
            if v["timeframe"] not in allowed_tfs:
                attempts += 1
                continue
            v["arch"]        = "v23"
            v["strategy"]    = "FinBuddyFreqAI_v23"
            v["freqaimodel"] = "LightGBMRegressor"
            v["config_file"] = TF_CONFIG_MAP_V23[v["timeframe"]]
        else:
            v["arch"]        = "v22"
            v["strategy"]    = "FinBuddyFreqAI"
            v["freqaimodel"] = "LightGBMClassifier"
            v["config_file"] = TF_CONFIG_MAP_V22[v["timeframe"]]
        if v == base:
            continue
        parent_metrics = parent["metrics"]
        rationale = (
            f"guided [{arch}]: derived from {parent['hypothesis_id'][:6]} "
            f"(profit={parent_metrics.get('profit_pct')}% WR={parent_metrics.get('wr',0)*100:.1f}%)"
        )
        out.append({"band": "aggressive", "rationale": rationale, "config": v,
                    "parent_id": parent["hypothesis_id"]})
    return out


def generate_aggressive_band(n: int = 12) -> list[dict]:
    """
    Mix:
      - 50% guided (perturbations around top-3 known results) — focus on promising regions
      - 50% pure-random (across full param space) — keeps exploring
    If no completed experiments yet, falls back to 100% pure-random.
    """
    n_guided = n // 2
    n_random = n - n_guided
    guided = _generate_guided_aggressive(n_guided)
    # If log is empty, guided returns []; use that budget for more random
    if not guided:
        n_random = n
    if V22_ENABLED:
        n_v23 = n_random // 2 + n_random % 2
        n_v22 = n_random // 2
        random_pool = _generate_aggressive_v23(n_v23) + _generate_aggressive_v22(n_v22)
    else:
        random_pool = _generate_aggressive_v23(n_random)
    return guided + random_pool


# ── Helpers ───────────────────────────────────────────────────────────────

def _current_best_config(arch: str | None = None) -> dict | None:
    """Current best-by-profit overall (or restricted to one architecture).

    Restricted to target_version='zscore' — the 268 legacy raw-% experiments
    have incompatible label distributions and must not seed the safe band.
    """
    from experiment_log import read_log
    log = [r for r in read_log()
           if r.get("status") == "completed"
           and r.get("config", {}).get("target_version") == "zscore"
           and r.get("metrics", {}).get("trades", 0) >= 20]
    if arch is not None:
        log = [r for r in log if (r.get("config", {}).get("arch") == arch
                                   or (arch == "v23" and r.get("config", {}).get("strategy") == "FinBuddyFreqAI_v23")
                                   or (arch == "v22" and r.get("config", {}).get("strategy") == "FinBuddyFreqAI"))]
    if not log:
        return None
    log.sort(key=lambda r: r["metrics"].get("profit_pct", -1e9), reverse=True)
    return log[0]["config"]


def _current_best_config_for_arch(arch: str) -> dict | None:
    return _current_best_config(arch=arch)


# ── Public API ────────────────────────────────────────────────────────────

def queue_seed_if_empty() -> int:
    """If queue and log are both empty, queue seed configs for enabled arches only."""
    from experiment_log import read_log, read_queue
    if read_log() or read_queue():
        return 0
    seeds = [SEED_CONFIG_V23]
    if V22_ENABLED:
        seeds.append(SEED_CONFIG_V22)
    queued = 0
    for seed in seeds:
        cfg = _stamp_target_version(seed)
        for win_name, timerange in WINDOWS.items():
            queue_hypothesis(
                config=cfg,
                band="seed",
                rationale=f"seed [{seed['arch']}]: baseline",
                window=win_name,
                timerange=timerange,
            )
            queued += 1
    return queued


def queue_v22_seeds() -> int:
    """One-shot helper to seed v22 hypotheses into an existing queue."""
    queued = 0
    for win_name, timerange in WINDOWS.items():
        queue_hypothesis(
            config=SEED_CONFIG_V22,
            band="seed",
            rationale="seed [v22]: live-config baseline (5m, classifier, balanced)",
            window=win_name,
            timerange=timerange,
        )
        queued += 1
    return queued


def _stamp_target_version(config: dict) -> dict:
    """Inject target_version into a config dict (v23 zscore, v22 raw_pct).

    Allows promote.py to exclude the 268 legacy raw-% experiments (which lack
    this field) from promotion decisions. Called before every queue_hypothesis().
    """
    arch = config.get("arch", "v23")
    if "target_version" not in config:
        config = dict(config)
        config["target_version"] = TARGET_VERSION if arch == "v23" else "raw_pct"
    return config


def generate_and_queue(safe_n: int = 6, aggressive_n: int = 6, windows: list[str] | None = None) -> int:
    """
    One brain cycle: generate safe + aggressive variants for BOTH architectures,
    queue on each window. Returns count of newly queued hypotheses.

    Window order matters for speed-to-promotion: each variant is queued as
    (bull_2024Q2, bear_2025Q1, bull_2025Q4, bear_2026Q1, bull_2024Q1) so that
    the runner always processes one bull → one bear back-to-back for every config.
    This means a promising config gets BOTH a bull and a bear result within ~3h
    instead of waiting for the entire bull backlog to drain first.

    PAIRED_WINDOWS order: best historical bull first, its matching bear second.
    bear_2026Q1 is the promotion gate (BEAR_2026Q1_REQUIRED) — included at position 4.
    bull_2024Q1 is the hardest bull and least informative early — placed last.
    """
    from experiment_log import read_queue as _rq
    # Paired window order: bull, bear, bull, bear, bull — tested back-to-back per config.
    PAIRED_WINDOWS = [
        "bull_2024Q2",  # primary bull validation (strongest bull signal historically)
        "bear_2025Q1",  # primary bear validation (best PF/WR on bear)
        "bull_2025Q4",  # secondary bull (recent, pre-2026-crash)
        "bear_2026Q1",  # promotion gate window (must pass WR≥50%)
        "bull_2024Q1",  # tertiary bull (earliest, hardest — placed last)
    ]
    target_windows = windows or PAIRED_WINDOWS
    safe = generate_safe_band_both(n_per_arch=safe_n // 2 + safe_n % 2)
    aggr = generate_aggressive_band(n=aggressive_n)
    all_variants = safe + aggr

    # Build set of (config_hash, window) already in queue to avoid re-queueing.
    from promote import _config_hash as _ch
    already_queued = {
        (_ch(r["config"]), r.get("window", ""))
        for r in _rq()
    }

    queued = 0
    for v in all_variants:
        cfg = _stamp_target_version(v["config"])
        for win_name in target_windows:
            if win_name not in WINDOWS:
                continue
            if (_ch(cfg), win_name) in already_queued:
                continue  # Fix 13: skip already-queued (config, window) pairs
            queue_hypothesis(
                config=cfg,
                band=v["band"],
                rationale=v["rationale"],
                window=win_name,
                timerange=WINDOWS[win_name],
                parent_id=v.get("parent_id"),
            )
            queued += 1
    return queued


if __name__ == "__main__":
    import json
    n = queue_seed_if_empty()
    if n > 0:
        print(f"Queued seed × {n} (both v22 + v23 × all windows)")
    else:
        added = generate_and_queue(safe_n=4, aggressive_n=6, windows=["bull_2024Q1", "bear_2025Q1"])
        print(f"Queued {added} new hypotheses")
