"""
hypothesis_gen.py — Generate new strategy variants for the brain to test.

Two bands of aggressiveness:

SAFE BAND — small perturbations around the current best-known config.
  Examples: long_threshold ±0.25, K_SL ±0.25, STABILITY_N ±1, timeframe held.
  Purpose: local search, gradient-descent-like refinement.

AGGRESSIVE BAND — wide combinatorial sweep + structural variants.
  Examples: switch timeframe, swap filters on/off, change label_period, try
  label scheme variants (return vs delta vs barrier).
  Purpose: discover non-local optima the safe band can't reach.

Both bands run in parallel — the brain isn't supposed to choose between them.
"""
from __future__ import annotations

import itertools
import json
import random
from pathlib import Path
from typing import Any

from experiment_log import queue_hypothesis, read_log, best_by_metric

# Bayesian optimisation via Optuna TPE. Graceful fallback if not installed.
try:
    import optuna
    import optuna.trial as _optuna_trial
    from optuna.distributions import (
        CategoricalDistribution as _Cat,
        FloatDistribution as _Float,
        IntDistribution as _Int,
    )
    optuna.logging.set_verbosity(optuna.logging.WARNING)
    _OPTUNA_AVAILABLE = True
except ImportError:
    _OPTUNA_AVAILABLE = False

# ──────────────────────────────────────────────────────────────────────────
# Architecture flags (2026-05-19): live bot moved to v23. v22 code kept on
# disk for history (same pattern as AiGuardrailStrategy / FinBuddyLLMModel)
# but no longer generated by the brain. Flip this flag back to True if you
# ever want parallel exploration again.
# ──────────────────────────────────────────────────────────────────────────
V22_ENABLED = False

# Analyst blacklist source — written every 6 h by scripts/brain/analyst.py
ANALYST_REPORT_PATH = Path(
    "/home/ubuntu/var/www/html/trade/finbuddy_memory/experiments/analyst_report.json"
)

# Data-coverage guard: skip a timeframe in random generation if its BTC
# feather file doesn't extend far enough to cover the active backtest windows.
DATA_DIR = Path("/home/ubuntu/var/www/html/trade/freqtrade/user_data/data/binance/futures")


def _load_analyst_blacklist() -> set[str]:
    """Return set of timeframes the analyst has flagged as dead/noisy.

    Falls through silently if the report doesn't exist yet (first runs).
    """
    try:
        data = json.loads(ANALYST_REPORT_PATH.read_text())
        findings = data.get("findings", {}) or {}
        return set(findings.get("dead_timeframes", [])) | set(findings.get("noisy_timeframes", []))
    except Exception:
        return set()


def _has_data_coverage(timeframe: str) -> bool:
    """Skip the timeframe if BTC's feather doesn't cover the backtest cutoff."""
    btc_file = DATA_DIR / f"BTC_USDT_USDT-{timeframe}-futures.feather"
    if not btc_file.exists():
        return False
    try:
        import pandas as pd
        df = pd.read_feather(btc_file)
        date_col = "date" if "date" in df.columns else df.columns[0]
        return str(df[date_col].max()) >= DATA_COVERAGE_CUTOFF
    except Exception:
        return False


def _available_timeframes(candidates: list[str]) -> list[str]:
    """Filter candidates by analyst blacklist + data coverage."""
    blacklist = _load_analyst_blacklist()
    return [tf for tf in candidates if tf not in blacklist and _has_data_coverage(tf)]


# ── Windows the brain evaluates on (3-month each, finish in <65min per runner) ──
# Mix of regimes for diversified evaluation. Each backtest must fit within the
# runner's 65-min lock window (BACKTEST_TIMEOUT_S=3900).
# NOTE (2026-05-22): added recent windows — prior windows only covered through
# 2025-04, missing 13 months of live market. Brain must evaluate on conditions
# it's actually deployed in.
# IMPORTANT: promote.py classifies windows by "bull"/"bear" substring in the
# window name. ALL window names here must include either "bull" or "bear" so
# they are correctly counted in the promotion gate logic.
# NOTE (2026-05-22): ALL prior experiments (268) used the old raw-% return target.
# Z-scored target added 2026-05-22. Old results have incompatible label distribution.
# New experiments carry target_version="zscore"; promote.py filters to zscore only.
DATA_COVERAGE_CUTOFF = "2026-01-01"  # ensure all windows have coverage
# WINDOW NAMING IS HONEST ABOUT DIRECTION (audited 2026-06-19 against the BTC 4h feather).
# promote.py classifies a window as bull/bear purely by the "bull"/"bear" substring in its
# NAME, and the gate requires ≥2 bull + ≥1 bear passing runs to prove the strategy is
# market-agnostic. Mislabeling a falling quarter "bull_*" silently lets a config satisfy the
# "bull" requirement on a down market — defeating the gate. The two former liars
# (bull_2024Q2 = actually −11%, bull_2025Q4 = actually −23%) were renamed to bear_* on
# 2026-06-19. Actual measured BTC return is in each comment below — keep it accurate on edits.
WINDOWS = {
    "bull_2024Q1": "20240101-20240401",   # BTC +68% — strong bull (halving run-up)
    "bull_2024Q4": "20241001-20250101",   # BTC +47% — post-election bull (added 2026-06-19, 36/38 pairs)
    "bear_2024Q2": "20240401-20240701",   # BTC -11% — mild down/chop (was mislabeled "bull_2024Q2")
    "bear_2025Q1": "20250101-20250401",   # BTC -12% — bear leg Q1 2025
    "bear_2025Q4": "20251001-20260101",   # BTC -23% — deep bear (was mislabeled "bull_2025Q4")
    "bear_2026Q1": "20260101-20260401",   # BTC -22% — declining Jan-Apr 2026 (live-condition window)
    # 2026-06-08: deep-history windows enabled by the 2020→present backfill. ~12 of 26 pairs
    # (the majors: BTC/ETH/SOL/XRP/LINK/ADA/DOT/LTC/AVAX/NEAR/FIL...) have data this far back —
    # FreqTrade backtest silently skips pairs without data, so these run on the majors.
    "bull_2021":   "20210101-20210401",   # 2021 parabolic euphoria — extreme bull (classified BULL)
    "crash_2022":  "20220501-20221231",   # LUNA (May) + FTX (Nov) — black-swan STRESS TEST.
                                          # Name intentionally has neither "bull" nor "bear":
                                          # promote.py ignores it for normal promotion averages;
                                          # it is a survival/drawdown gate, inspected separately.
}

# Window order for queue generation: bull→bear pairs so the runner tests
# each config on one bull AND one bear back-to-back (~3h to both results).
# REBALANCED 2026-06-19 to use GENUINE bull windows. The old rotation used
# bull_2024Q2 (−11%) and bull_2025Q4 (−23%) as its "bull" representatives — both
# were actually DOWN markets, so the brain's day-to-day "bull" validation never
# tested an up-market. Now: bull_2024Q1 (+68%) + bull_2024Q4 (+47%) are the real
# bulls; bear_2025Q1 + bear_2026Q1 (the live-condition gate) are the bears. 2:2
# balance keeps next_alternating() from exhausting the bear queue (the 2026-06-04 bug).
PAIRED_WINDOWS = [
    "bull_2024Q1",   # genuine bull (+68%)
    "bear_2025Q1",   # genuine bear (−12%)
    "bull_2024Q4",   # genuine bull (+47%, recent → 36/38 pair coverage)
    "bear_2026Q1",   # promotion gate window (must pass WR≥50%), live-condition bear
]

# Target version tag — added to every new queued experiment so promote.py can
# exclude the 268 legacy raw-% experiments (which have no target_version field).
TARGET_VERSION = "zscore"

# ══════════════════════════════════════════════════════════════════════════
# Two architectures live in the brain. Each has its own seed + param space.
# Brain explores BOTH in parallel — vision says broader perspective wins.
# ══════════════════════════════════════════════════════════════════════════

# v23 Regression — LightGBMRegressor predicting future_return %
def _active_tf_and_config(default_tf="15m", default_cfg="v23_regression_15m_di_config.json"):
    """Active timeframe + its config file from the single source of truth
    (finbuddy_memory/timeframe_profiles.json — set by the dashboard switcher). The brain SEED
    follows the live timeframe; the AGGRESSIVE band still explores all timeframes."""
    try:
        p = Path(__file__).resolve().parents[2] / "finbuddy_memory" / "timeframe_profiles.json"
        d = json.loads(p.read_text())
        tf = d.get("active", default_tf)
        return tf, d.get("profiles", {}).get(tf, {}).get("config_file", default_cfg)
    except Exception:
        return default_tf, default_cfg


_ACTIVE_TF, _ACTIVE_CFG = _active_tf_and_config()

SEED_CONFIG_V23 = {
    "arch":               "v23",
    "strategy":           "CortexaAI_v23",
    "freqaimodel":        "LightGBMRegressor",
    "config_file":        _ACTIVE_CFG,   # follows active timeframe (single source of truth)
    "timeframe":          _ACTIVE_TF,
    "long_threshold":     0.3,    # FIXED 2026-06-08: _GLOBAL_STD=0.30, std_factor capped at 1.0.
                                  # effective = 0.3×1.3×0.5=0.195 (degenerate pairs) → 0.3×1.3×1.0=0.39 (normal).
                                  # ETH (std=0.33, centered=0.538): fires long at 0.390. LT=0.5 → threshold 0.65 → blocked.
    "short_threshold":    -0.3,   # Symmetric with LT.
    "k_sl":               2.0,
    "k_tp":               3.0,   # raised from 2.0 — WF shows WR=61% but PF=0.77 (exits too early)
    "stability_n":        2,
    "label_period_candles": 12,
    # FIXED 2026-08-31: both defaulted True, matching the live bot's setting until 2026-06-12 —
    # when DI_threshold=0/use_SVM_to_remove_outliers=False was applied live after SVM was found
    # flagging 100% of candles as outliers (do_predict=0 outage). That fix was never carried over
    # to the brain's own baseline. Confirmed via two direct A/B diagnostics (bull_2024Q4, both
    # trend_vol and standard absolute-mode entry): filter_di=True suppressed ALL long entries on
    # strongly-trending candles (long_count 0→238 and 0→224 just from flipping this off, else-
    # identical config) — DI/SVM outlier filtering treats a genuine strong rally as "out of
    # distribution" relative to calmer training data. Any past experiment run with filter_di=True
    # may have had artificially suppressed longs; treat filter_di=True historical results with
    # long_count=0 or low as suspect, not as evidence the config itself is long-averse.
    "filter_di":          False,
    "filter_svm":         False,
    "feature_set":        "all",   # which external features to include (see strategy FREQAI_FEATURE_SET)
    "n_estimators":       100,     # stamped so A/B comparisons are possible in experiment logs
}

# v22 Classifier+LLM — RETIRED 2026-05-19. v23 regression is live. V22_ENABLED=False keeps this dead.
# Kept for historical reference only. Do not re-enable without verifying brain config + windows.
SEED_CONFIG_V22 = {
    "arch":               "v22",
    "strategy":           "FinBuddyFreqAI",
    "freqaimodel":        "LightGBMClassifier",   # pure backtest; live wraps with LLM
    "config_file":        "v22_backtest_config.json",
    "timeframe":          "5m",
    "k_tp":               2.0,
    "k_sl":               1.0,
    "ml_threshold":       0.60,
    "label_period_candles": 72,
}

# Back-compat alias
SEED_CONFIG = SEED_CONFIG_V23


# ── SAFE BAND (architecture-aware) ────────────────────────────────────────

# Per-architecture perturbation menus. Each tuple: (param, delta, rationale).
PERTURB_V23 = [
    ("long_threshold",      +0.25, "tighter long entries"),
    ("long_threshold",      -0.25, "looser long entries"),
    ("short_threshold",     -0.25, "tighter short entries"),
    ("short_threshold",     +0.25, "looser short entries"),
    ("k_sl",                +0.25, "wider stop"),
    ("k_sl",                -0.25, "tighter stop"),
    ("k_tp",                +0.25, "more upside on trail"),
    ("k_tp",                -0.25, "tighter trail lock"),
    ("stability_n",         +1,    "stricter signal stability"),
    ("stability_n",         -1,    "looser signal stability"),
]

PERTURB_V22 = [
    ("k_tp",                +0.25, "wider take-profit"),
    ("k_tp",                -0.25, "tighter take-profit"),
    ("k_sl",                +0.20, "wider stop"),
    ("k_sl",                -0.20, "tighter stop"),
    ("ml_threshold",        +0.05, "tighter classifier threshold"),
    ("ml_threshold",        -0.05, "looser classifier threshold"),
]


# B2 (2026-06-11): exhausted-family gate. After this many unsuccessful runs of
# the same (window, model-shape) family, param-only tweaks are refused there.
EXHAUSTED_FAMILY_LIMIT = 40

# Fields that change WHAT the model learns (vs. how the strategy trades it).
# Two configs differing only outside this set are the same "family".
_MODEL_SHAPE_KEYS = (
    "arch", "strategy", "freqaimodel", "timeframe", "feature_set",
    "label_period_candles", "filter_di", "filter_svm",
    "prune_indicators", "perpair_oi", "target_version",
    # entry_mode is mechanism, not parameter: quantile entries are a new search
    # space and get their own failure budget separate from absolute thresholds.
    "entry_mode",
)


def _family_key(cfg: dict, window: str) -> tuple:
    return (window,) + tuple(repr(cfg.get(k)) for k in _MODEL_SHAPE_KEYS)


def _notify_family_exhausted(cfg: dict, window: str, n_failures: int) -> None:
    """One-line Telegram when a search family is declared exhausted (best-effort)."""
    try:
        import sys as _sys
        from pathlib import Path as _Path
        _sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
        from lib.telegram_template import Subsystem, Status, send
        send(
            Subsystem.BRAIN_CYCLE, Status.WARN,
            f"Search family exhausted on {window}",
            fields={
                "Failures": n_failures,
                "Timeframe": cfg.get("timeframe"),
                "Feature set": cfg.get("feature_set"),
            },
            context="Param-only configs refused here. New experiments need a "
                    "changed feature set, strategy, or timeframe.",
            silent=True,
        )
    except Exception:
        pass


# Valid threshold scale for the z-score era (_GLOBAL_STD=0.30, fixed 2026-06-08).
# Configs outside these bounds are from the retired raw-%/0.95-std scale and must
# neither be queued nor used as parents for guided/bayes exploration.
LT_BOUNDS = (0.1, 0.8)
ST_BOUNDS = (-1.0, -0.1)


def _in_current_scale(config: dict) -> bool:
    """True if a config's thresholds fall inside the current valid z-score scale."""
    lt = config.get("long_threshold")
    st = config.get("short_threshold")
    if lt is not None and not (LT_BOUNDS[0] <= lt <= LT_BOUNDS[1]):
        return False
    if st is not None and not (ST_BOUNDS[0] <= st <= ST_BOUNDS[1]):
        return False
    return True


def _clamp(v: dict, param: str) -> dict:
    """Clamp a perturbed param to a sane range."""
    if "threshold" == param.split("_")[-1] and param != "ml_threshold":
        if param == "short_threshold":
            # FIXED 2026-06-08: _GLOBAL_STD=0.30; max useful ST=-1.0 (effective -0.65σ in mature model)
            v[param] = max(ST_BOUNDS[0], min(ST_BOUNDS[1], v[param]))
        else:
            # FIXED 2026-06-08: max useful LT=0.8 (effective 0.52 in immature, 1.04 in mature model)
            v[param] = max(LT_BOUNDS[0], min(LT_BOUNDS[1], v[param]))
    elif param == "ml_threshold":
        v[param] = max(0.45, min(0.85, v[param]))
    elif param.startswith("k_"):
        v[param] = max(0.5, min(4.0, v[param]))
    elif param == "stability_n":
        # Bug 4 fix (2026-05-30): clamp to [1, 4]. stability_n=-1 was being
        # queued (perturbation -1 from base=1), which the strategy silently
        # corrects to 1 via max(1,n) — but the config_hash stores -1, causing
        # confusion in logs and any future promotion. Min=1 is the valid floor.
        v[param] = max(1, min(4, int(v[param])))
    return v


def generate_safe_band(seed: dict | None = None, n: int = 8) -> list[dict]:
    """Small perturbations around the current best config — for the SAME architecture."""
    base = dict(seed or _current_best_config() or SEED_CONFIG_V23)
    # Older log entries don't have 'arch' — infer from strategy name
    if "arch" not in base:
        base["arch"] = "v22" if base.get("strategy") == "FinBuddyFreqAI" else "v23"

    # FIXED 2026-06-08: With _GLOBAL_STD=0.30, max useful LT=0.8. Any config with LT>0.8
    # will produce near-zero longs (effective threshold > 1.04 in mature model).
    # Override to seed LT (0.5) when anchoring on stale high-LT configs.
    if base.get("arch", "v23") == "v23" and base.get("long_threshold", 0.3) > 0.8:
        base = dict(base)
        base["long_threshold"] = SEED_CONFIG_V23["long_threshold"]  # 0.5

    perturbations = PERTURB_V22 if base["arch"] == "v22" else PERTURB_V23

    random.shuffle(perturbations)
    out = []
    for (param, delta, rationale) in perturbations[:n]:
        v = dict(base)
        if param not in v:
            continue
        if isinstance(v[param], int):
            v[param] = max(1, int(v[param] + delta))
        else:
            v[param] = round(float(v[param]) + float(delta), 3)
            v = _clamp(v, param)
        if v == base:
            continue
        out.append({
            "band": "safe",
            "rationale": f"safe [{base['arch']}]: {param} {'+' if delta>=0 else ''}{delta} ({rationale})",
            "config": v,
        })
    return out


def generate_safe_band_both(n_per_arch: int = 4) -> list[dict]:
    """SAFE band for active architectures (v22 skipped when V22_ENABLED=False).

    Seed each architecture from its own current-best. Disabled arches are
    silently skipped — same pattern as N8N pipeline retirement: code stays,
    flag flips off.
    """
    arch_seeds = [SEED_CONFIG_V23]
    if V22_ENABLED:
        arch_seeds.insert(0, SEED_CONFIG_V22)
    out = []
    for arch_seed in arch_seeds:
        best = _current_best_config_for_arch(arch_seed["arch"]) or arch_seed
        out += generate_safe_band(seed=best, n=n_per_arch)
    return out


# ── AGGRESSIVE BAND (architecture-aware) ──────────────────────────────────

AGGRESSIVE_CHOICES_V23 = {
    "timeframe":          ["5m", "15m", "30m", "1h", "4h"],
    # FIXED 2026-06-08: _GLOBAL_STD=0.30 (z-score era). Effective threshold = LT × combined × std_factor.
    # With std_factor=0.5 (immature model, pred_std < 0.30): effective = LT × 1.3 × 0.5.
    # With std_factor=1.0 (mature model, pred_std=0.30): effective = LT × 1.3 × 1.0.
    # Max useful LT = 0.7 → effective = 0.91 (2-3% of candles per pair). LT > 0.8 rarely fires.
    "long_threshold":     [0.2, 0.3, 0.5, 0.7],
    "short_threshold":    [-0.2, -0.3, -0.5, -0.7, -1.0],
    "k_sl":               [1.0, 1.5, 2.0, 2.5, 3.0],
    "k_tp":               [1.5, 2.0, 2.5, 3.0],
    "stability_n":        [1, 2, 3, 4],
    "label_period_candles": [12, 24, 48, 72, 144],
    # FIXED 2026-08-31: True removed from the search space — confirmed to suppress ALL long
    # entries on strongly-trending candles (see SEED_CONFIG_V23 comment above), the same bug
    # already fixed live 2026-06-12. Not a legitimate lever to explore, matches live's setting.
    "filter_di":          [False],
    "filter_svm":         [False],
    "feature_set":        ["all", "no_regime"],
    # LightGBM tree hyperparameters — previously locked, now swept by brain
    # Lower num_leaves = more regularized (less overfit); lower lr = better generalisation
    "num_leaves":         [15, 31, 63, 127],
    "learning_rate":      [0.01, 0.03, 0.05],
}

AGGRESSIVE_CHOICES_V22 = {
    "timeframe":          ["5m", "15m", "30m", "1h"],     # 4h underperforms v22-style classifier
    "k_tp":               [1.5, 2.0, 2.5, 3.0],
    "k_sl":               [0.8, 1.0, 1.2, 1.5, 2.0],
    "ml_threshold":       [0.55, 0.60, 0.65, 0.70, 0.75],
    "label_period_candles": [6, 12, 24, 48, 72],
}

# Timeframe → config file map (per architecture)
TF_CONFIG_MAP_V23 = {
    "5m":  "backtest_config.json",
    "15m": "v23_regression_15m_di_config.json",
    "30m": "v23_regression_30m_config.json",
    "1h":  "v23_regression_1h_config.json",
    "4h":  "v23_regression_4h_config.json",
}

TF_CONFIG_MAP_V22 = {
    # All v22 variants share v22_backtest_config.json but override timeframe via env.
    # FreqTrade respects --timeframe CLI arg over config's timeframe.
    "5m":  "v22_backtest_config.json",
    "15m": "v22_backtest_config.json",
    "30m": "v22_backtest_config.json",
    "1h":  "v22_backtest_config.json",
}


def _generate_aggressive_v23(n: int) -> list[dict]:
    # Filter the timeframe pool by analyst blacklist + actual data coverage.
    allowed_tfs = _available_timeframes(AGGRESSIVE_CHOICES_V23["timeframe"])
    if not allowed_tfs:
        # No timeframe survives gating — fall back to the seed default so the
        # brain keeps making progress instead of generating zero hypotheses.
        allowed_tfs = [SEED_CONFIG_V23["timeframe"]]
    out, seen = [], set()
    attempts = 0
    while len(out) < n and attempts < n * 5:
        attempts += 1
        v = {k: random.choice(c) for k, c in AGGRESSIVE_CHOICES_V23.items()}
        v["timeframe"] = random.choice(allowed_tfs)
        v["short_threshold"] = -abs(v["short_threshold"])
        v["arch"] = "v23"
        v["strategy"]    = "CortexaAI_v23"
        v["freqaimodel"] = "LightGBMRegressor"
        v["config_file"] = TF_CONFIG_MAP_V23[v["timeframe"]]
        key = tuple(sorted(v.items()))
        if key in seen:
            continue
        seen.add(key)
        rationale = (
            f"aggr [v23]: tf={v['timeframe']} lt={v['long_threshold']:+} st={v['short_threshold']:+} "
            f"ksl={v['k_sl']} ktp={v['k_tp']} N={v['stability_n']} lp={v['label_period_candles']} "
            f"di={v['filter_di']} svm={v['filter_svm']} feat={v.get('feature_set','all')}"
        )
        out.append({"band": "aggressive", "rationale": rationale, "config": v})
    return out


def _generate_aggressive_v22(n: int) -> list[dict]:
    out, seen = [], set()
    attempts = 0
    while len(out) < n and attempts < n * 5:
        attempts += 1
        v = {k: random.choice(c) for k, c in AGGRESSIVE_CHOICES_V22.items()}
        v["arch"] = "v22"
        v["strategy"]    = "FinBuddyFreqAI"
        v["freqaimodel"] = "LightGBMClassifier"
        v["config_file"] = TF_CONFIG_MAP_V22[v["timeframe"]]
        key = tuple(sorted(v.items()))
        if key in seen:
            continue
        seen.add(key)
        rationale = (
            f"aggr [v22]: tf={v['timeframe']} ktp={v['k_tp']} ksl={v['k_sl']} "
            f"thr={v['ml_threshold']} lp={v['label_period_candles']}"
        )
        out.append({"band": "aggressive", "rationale": rationale, "config": v})
    return out


def _top_k_results(k: int = 3, min_trades: int = 20) -> list[dict]:
    """Return top-K zscore experiments by profit_pct (filtered by min trade count).

    Restricted to target_version='zscore' only — the 268 legacy raw-% experiments
    have incompatible label distributions and must not seed guided exploration.
    """
    log = [r for r in read_log()
           if r.get("status") == "completed"
           and r.get("config", {}).get("target_version") == "zscore"
           and r.get("metrics", {}).get("trades", 0) >= min_trades
           # Old-scale configs (e.g. lt=3.0/3.25 from the _GLOBAL_STD=0.95 era) must
           # not parent children: their thresholds are unreachable on the current
           # scale, so every derived config wastes a full 26-pair run.
           and _in_current_scale(r.get("config", {}))]
    if not log:
        return []
    log.sort(key=lambda r: r["metrics"].get("profit_pct", -1e9), reverse=True)
    return log[:k]


def _generate_guided_aggressive(n: int) -> list[dict]:
    """
    Guided exploration — pick top-K from experiment log and generate medium
    perturbations around each (between safe-band ±0.25 and aggressive random).
    Focuses compute on promising regions instead of pure-random sweep.
    """
    top = _top_k_results(k=3)
    if not top:
        return []  # no signal yet — caller falls back to pure-random aggressive
    out = []
    attempts = 0
    while len(out) < n and attempts < n * 8:
        attempts += 1
        parent = random.choice(top)
        base = dict(parent["config"])
        arch = base.get("arch") or ("v22" if base.get("strategy") == "FinBuddyFreqAI" else "v23")
        choices = AGGRESSIVE_CHOICES_V22 if arch == "v22" else AGGRESSIVE_CHOICES_V23
        # Mutate 2 random dimensions with medium step (one notch in the choice list)
        v = dict(base)
        for param in random.sample(list(choices.keys()), k=min(2, len(choices))):
            opts = choices[param]
            if v.get(param) in opts:
                idx = opts.index(v[param])
                step = random.choice([-1, 1])
                v[param] = opts[max(0, min(len(opts) - 1, idx + step))]
            else:
                v[param] = random.choice(opts)
        if arch == "v23":
            v["short_threshold"] = -abs(v["short_threshold"])
            # Drop guided mutations that land on a dead/blacklisted timeframe.
            # _generate_aggressive_v23 already filters via _available_timeframes(),
            # but guided exploration mutates params one-by-one and can step from
            # '15m' into '5m' or '30m' which the analyst has flagged as dead.
            allowed_tfs = _available_timeframes(AGGRESSIVE_CHOICES_V23["timeframe"])
            if v["timeframe"] not in allowed_tfs:
                attempts += 1
                continue
            v["arch"]        = "v23"
            v["strategy"]    = "CortexaAI_v23"
            v["freqaimodel"] = "LightGBMRegressor"
            v["config_file"] = TF_CONFIG_MAP_V23[v["timeframe"]]
        else:
            v["arch"]        = "v22"
            v["strategy"]    = "FinBuddyFreqAI"
            v["freqaimodel"] = "LightGBMClassifier"
            v["config_file"] = TF_CONFIG_MAP_V22[v["timeframe"]]
        if v == base:
            continue
        parent_metrics = parent["metrics"]
        rationale = (
            f"guided [{arch}]: derived from {parent['hypothesis_id'][:6]} "
            f"(profit={parent_metrics.get('profit_pct')}% WR={parent_metrics.get('wr',0)*100:.1f}%)"
        )
        out.append({"band": "aggressive", "rationale": rationale, "config": v,
                    "parent_id": parent["hypothesis_id"]})
    return out


# ── BAYESIAN BAND ─────────────────────────────────────────────────────────

# Minimum completed-experiment count before Bayesian activates.
# TPESampler needs this many "startup" random trials before its surrogate
# model is reliable; below this it behaves like random search anyway.
_BAYES_MIN_TRIALS = 30


def _bayes_score(metrics: dict) -> float:
    """Composite score for the Optuna objective (higher = better).

    Sharpe is the primary axis (risk-adjusted).  A trade-count confidence
    weight shrinks configs with fewer than 30 trades toward 0 so the TPE
    doesn't over-fit on noisy small samples.  Positive profit adds a small
    bonus; negative profit is not double-penalised (Sharpe already captures it).
    """
    trades = metrics.get("trades", 0)
    if trades < 10:
        return -2.0  # tell TPE to avoid this region
    sharpe = float(metrics.get("sharpe") or -2.0)
    profit = float(metrics.get("profit_pct") or -2.0)
    conf   = min(trades / 30.0, 1.0)          # full confidence at 30+ trades
    bonus  = 1.0 + max(0.0, profit) / 100.0   # small upside for profitability
    return sharpe * conf * bonus


def _make_distributions(allowed_tfs: list[str]) -> dict:
    """Optuna distributions that mirror AGGRESSIVE_CHOICES_V23.

    short_threshold is stored as a positive absolute value ('short_threshold_abs')
    and negated when the config dict is assembled — Optuna only handles bounded
    numerical ranges cleanly with positive numbers.
    """
    if not _OPTUNA_AVAILABLE:
        return {}
    return {
        "long_threshold":       _Float(0.1, 0.8, step=0.1),   # FIXED 2026-06-08: _GLOBAL_STD=0.30, max useful LT=0.8
        "short_threshold_abs":  _Float(0.1, 1.0, step=0.1),   # symmetric with LT scale
        "k_sl":                 _Float(0.5,  4.0,  step=0.25),
        "k_tp":                 _Float(1.0,  4.0,  step=0.25),
        "stability_n":          _Int(1, 4),
        "label_period_candles": _Cat([12, 24, 48, 72, 144]),
        # FIXED 2026-08-31: True removed, same fix as AGGRESSIVE_CHOICES_V23 above.
        "filter_di":            _Cat([False]),
        "filter_svm":           _Cat([False]),
        "num_leaves":           _Cat([15, 31, 63, 127]),
        "learning_rate":        _Cat([0.01, 0.03, 0.05]),
        "feature_set":          _Cat(["all", "no_regime"]),
        "timeframe":            _Cat(allowed_tfs),
    }


def _snap(value: object, dist: object) -> object | None:
    """Coerce a legacy param value to the nearest valid point in a distribution.

    Returns None if the value is outside the distribution's range/choices,
    which causes the caller to skip that past experiment (rather than crash).
    """
    if not _OPTUNA_AVAILABLE:
        return None
    if isinstance(dist, _Cat):
        return value if value in dist.choices else None
    if isinstance(dist, _Float):
        v = float(value)
        # Out-of-range legacy values (e.g. lt=3.0 from the old scale) must be
        # SKIPPED, not clamped — clamping attributed old-scale scores to the
        # boundary value (lt=0.8), poisoning TPE's surrogate toward that region.
        if v < dist.low - 1e-9 or v > dist.high + 1e-9:
            return None
        if dist.step:
            lo, step = dist.low, dist.step
            snapped = round(round((v - lo) / step) * step + lo, 8)
            snapped = round(max(dist.low, min(dist.high, snapped)), 6)
            return snapped
        return v
    if isinstance(dist, _Int):
        i = int(value)
        if i < dist.low or i > dist.high:
            return None
        return i
    return None


def _build_study(completed: list[dict], distributions: dict):
    """Reconstruct an in-memory Optuna study from past experiment results.

    Each completed experiment becomes a FrozenTrial so TPE's surrogate model
    is initialised with all ~380 real results instead of starting cold.
    Returns (study, n_loaded) where n_loaded is how many trials were imported.
    """
    study = optuna.create_study(
        direction="maximize",
        sampler=optuna.samplers.TPESampler(
            seed=42,
            n_startup_trials=_BAYES_MIN_TRIALS,
        ),
    )
    n_loaded = 0
    for exp in completed:
        cfg     = exp.get("config", {})
        metrics = exp.get("metrics") or {}
        score   = _bayes_score(metrics)
        try:
            raw = {
                "long_threshold":       cfg.get("long_threshold",      1.5),
                "short_threshold_abs":  abs(float(cfg.get("short_threshold", -1.5))),
                "k_sl":                 cfg.get("k_sl",                2.0),
                "k_tp":                 cfg.get("k_tp",                2.0),
                "stability_n":          cfg.get("stability_n",         2),
                "label_period_candles": cfg.get("label_period_candles",12),
                "filter_di":            cfg.get("filter_di",           True),
                "filter_svm":           cfg.get("filter_svm",          True),
                "num_leaves":           cfg.get("num_leaves",          31),
                "learning_rate":        cfg.get("learning_rate",       0.03),
                "feature_set":          cfg.get("feature_set",         "all"),
                "timeframe":            cfg.get("timeframe",           "15m"),
            }
            params = {}
            valid  = True
            for k, dist in distributions.items():
                snapped = _snap(raw[k], dist)
                if snapped is None:
                    valid = False
                    break
                params[k] = snapped
            if not valid:
                continue
            trial = _optuna_trial.create_trial(
                params=params,
                distributions=distributions,
                value=score,
            )
            study.add_trial(trial)
            n_loaded += 1
        except Exception:
            continue
    return study, n_loaded


def generate_bayesian(n: int, allowed_tfs: list[str] | None = None) -> list[dict]:
    """Generate n hypotheses using Optuna TPE Bayesian optimisation.

    Workflow:
      1. Load all completed zscore experiments from log.jsonl as Optuna trials.
      2. Ask TPE to suggest the next n most-promising parameter sets.
      3. Return them formatted as hypothesis dicts (same shape as safe/aggressive).

    Falls back to [] if:
      - optuna is not installed
      - fewer than _BAYES_MIN_TRIALS (30) completed results exist (TPE is just
        random search below this; random band already handles that case)

    Called every 6h from generate_aggressive_band() once the brain has enough
    data.  The study is rebuilt from disk each call — no persistent DB needed.
    """
    if not _OPTUNA_AVAILABLE:
        return []

    if allowed_tfs is None:
        allowed_tfs = _available_timeframes(AGGRESSIVE_CHOICES_V23["timeframe"])
    if not allowed_tfs:
        allowed_tfs = [SEED_CONFIG_V23["timeframe"]]

    completed = [
        r for r in read_log()
        if r.get("status") == "completed"
        and r.get("config", {}).get("target_version") == "zscore"
        and r.get("metrics") is not None
    ]
    if len(completed) < _BAYES_MIN_TRIALS:
        return []

    distributions = _make_distributions(allowed_tfs)
    study, n_loaded = _build_study(completed, distributions)

    out: list[dict] = []
    seen: set[tuple] = set()
    attempts = 0

    while len(out) < n and attempts < n * 6:
        attempts += 1
        trial = study.ask(fixed_distributions=distributions)
        p     = trial.params

        tf = p["timeframe"]
        v  = {
            "arch":                  "v23",
            "strategy":              "CortexaAI_v23",
            "freqaimodel":           "LightGBMRegressor",
            "config_file":           TF_CONFIG_MAP_V23.get(tf, "v23_regression_15m_di_config.json"),
            "timeframe":             tf,
            "long_threshold":        p["long_threshold"],
            "short_threshold":      -p["short_threshold_abs"],
            "k_sl":                  p["k_sl"],
            "k_tp":                  p["k_tp"],
            "stability_n":           p["stability_n"],
            "label_period_candles":  p["label_period_candles"],
            "filter_di":             p["filter_di"],
            "filter_svm":            p["filter_svm"],
            "num_leaves":            p["num_leaves"],
            "learning_rate":         p["learning_rate"],
            "feature_set":           p["feature_set"],
            "n_estimators":          100,
        }
        key = tuple(sorted(v.items()))
        if key in seen:
            # Duplicate — tell study with neutral score and skip
            study.tell(trial, 0.0)
            continue
        seen.add(key)

        # Tell the study a placeholder score so TPE diversifies subsequent asks.
        # Using 0.0 (break-even Sharpe) is deliberately neutral — we don't want
        # to reward or punish the suggestion before we've actually run it.
        study.tell(trial, 0.0)

        rationale = (
            f"bayes [v23]: lt={v['long_threshold']:+.2f} st={v['short_threshold']:+.2f} "
            f"ksl={v['k_sl']} ktp={v['k_tp']} N={v['stability_n']} "
            f"lp={v['label_period_candles']} tf={tf} "
            f"leaves={v['num_leaves']} lr={v['learning_rate']} "
            f"({n_loaded} past trials)"
        )
        out.append({"band": "aggressive", "rationale": rationale, "config": v})

    return out


def generate_aggressive_band(n: int = 12) -> list[dict]:
    """Mix of three search strategies in a 1/3 : 1/3 : 1/3 split:

      GUIDED  (1/3) — medium perturbations around top-K known results.
                      Local refinement; finds the bottom of a known valley fast.
      BAYESIAN (1/3) — Optuna TPE global search informed by all past results.
                       Learns which parameter *combinations* work; directs budget
                       toward high-Sharpe regions the random search would miss.
                       Activates once ≥30 completed experiments exist; below that
                       its budget falls through to RANDOM (cold-start safe).
      RANDOM  (1/3) — pure-random sweep across full param space.
                      Exploration insurance so the brain never gets trapped in a
                      local optimum discovered by the other two strategies.

    All three strategies use the same output schema so the runner, queue, and
    promotion pipeline see no difference.
    """
    n_each   = n // 3
    n_guided = n_each
    n_bayes  = n_each
    n_random = n - n_guided - n_bayes   # absorbs rounding remainder

    guided  = _generate_guided_aggressive(n_guided)
    # If no log yet, guided returns []; roll its budget into random
    if not guided:
        n_random += n_guided

    allowed_tfs = _available_timeframes(AGGRESSIVE_CHOICES_V23["timeframe"])
    bayes   = generate_bayesian(n_bayes, allowed_tfs=allowed_tfs)
    # If Bayesian returns [] (cold start / optuna missing), roll into random
    if not bayes:
        n_random += n_bayes

    if V22_ENABLED:
        n_v23 = n_random // 2 + n_random % 2
        n_v22 = n_random // 2
        random_pool = _generate_aggressive_v23(n_v23) + _generate_aggressive_v22(n_v22)
    else:
        random_pool = _generate_aggressive_v23(n_random)

    return guided + bayes + random_pool


# ── Helpers ───────────────────────────────────────────────────────────────

def _current_best_config(arch: str | None = None) -> dict | None:
    """Current best-by-profit overall (or restricted to one architecture).

    Restricted to target_version='zscore' — the 268 legacy raw-% experiments
    have incompatible label distributions and must not seed the safe band.
    """
    from experiment_log import read_log
    log = [r for r in read_log()
           if r.get("status") == "completed"
           and r.get("config", {}).get("target_version") == "zscore"
           and r.get("metrics", {}).get("trades", 0) >= 20]
    if arch is not None:
        log = [r for r in log if (r.get("config", {}).get("arch") == arch
                                   or (arch == "v23" and r.get("config", {}).get("strategy") == "CortexaAI_v23")
                                   or (arch == "v22" and r.get("config", {}).get("strategy") == "FinBuddyFreqAI"))]
    if not log:
        return None
    log.sort(key=lambda r: r["metrics"].get("profit_pct", -1e9), reverse=True)
    return log[0]["config"]


def _current_best_config_for_arch(arch: str) -> dict | None:
    return _current_best_config(arch=arch)


# ── Public API ────────────────────────────────────────────────────────────

def queue_seed_if_empty() -> int:
    """If queue and log are both empty, queue seed configs for enabled arches only."""
    from experiment_log import read_log, read_queue
    if read_log() or read_queue():
        return 0
    seeds = [SEED_CONFIG_V23]
    if V22_ENABLED:
        seeds.append(SEED_CONFIG_V22)
    queued = 0
    for seed in seeds:
        cfg = _stamp_target_version(seed)
        for win_name, timerange in WINDOWS.items():
            queue_hypothesis(
                config=cfg,
                band="seed",
                rationale=f"seed [{seed['arch']}]: baseline",
                window=win_name,
                timerange=timerange,
            )
            queued += 1
    return queued


def queue_v22_seeds() -> int:
    """One-shot helper to seed v22 hypotheses into an existing queue."""
    queued = 0
    for win_name, timerange in WINDOWS.items():
        queue_hypothesis(
            config=SEED_CONFIG_V22,
            band="seed",
            rationale="seed [v22]: live-config baseline (5m, classifier, balanced)",
            window=win_name,
            timerange=timerange,
        )
        queued += 1
    return queued


def _stamp_target_version(config: dict) -> dict:
    """Inject target_version into a config dict (v23 zscore, v22 raw_pct).

    Allows promote.py to exclude the 268 legacy raw-% experiments (which lack
    this field) from promotion decisions. Called before every queue_hypothesis().
    """
    arch = config.get("arch", "v23")
    if "target_version" not in config:
        config = dict(config)
        config["target_version"] = TARGET_VERSION if arch == "v23" else "raw_pct"
    return config


def generate_and_queue(safe_n: int = 6, aggressive_n: int = 6, windows: list[str] | None = None) -> int:
    """
    One brain cycle: generate safe + aggressive variants for BOTH architectures,
    queue on each window. Returns count of newly queued hypotheses.

    Window order matters for speed-to-promotion: each variant is queued as
    (bull_2024Q1, bear_2025Q1, bull_2024Q4, bear_2026Q1) so that the runner always
    processes one bull → one bear back-to-back for every config. This means a
    promising config gets BOTH a bull and a bear result within ~3h instead of
    waiting for the entire bull backlog to drain first.

    REBALANCED 2026-06-19: now uses GENUINE bull windows (bull_2024Q1 +68%,
    bull_2024Q4 +47%). The old rotation's "bull" slots (bull_2024Q2, bull_2025Q4)
    were actually −11% and −23% down markets — renamed to bear_* and dropped here.
    bear_2026Q1 is the promotion gate (BEAR_2026Q1_REQUIRED). 2:2 balance keeps
    next_alternating() from exhausting the bear queue.
    """
    from experiment_log import read_queue as _rq
    # Paired window order: bull, bear, bull, bear — tested back-to-back per config.
    PAIRED_WINDOWS = [
        "bull_2024Q1",  # genuine bull (+68%, halving run-up)
        "bear_2025Q1",  # genuine bear (−12%, best PF/WR on bear historically)
        "bull_2024Q4",  # genuine bull (+47%, recent → 36/38 pair coverage)
        "bear_2026Q1",  # promotion gate window (must pass WR≥50%), live-condition bear
        # 2:2 balance ensures next_alternating() always finds a bear entry (2026-06-04 fix).
    ]
    target_windows = windows or PAIRED_WINDOWS
    safe = generate_safe_band_both(n_per_arch=safe_n // 2 + safe_n % 2)
    aggr = generate_aggressive_band(n=aggressive_n)
    all_variants = safe + aggr

    # Build set of (config_hash, window) already in queue to avoid re-queueing.
    from promote import _config_hash as _ch
    already_queued = {
        (_ch(r["config"]), r.get("window", ""))
        for r in _rq()
    }

    # B2 (2026-06-11): refuse param-only experiments on exhausted families.
    # A "family" is (window, model-shaping fields). Once a family has accumulated
    # EXHAUSTED_FAMILY_LIMIT unsuccessful runs, more threshold/geometry tweaks
    # inside it are statistically pointless — new experiments there require a
    # changed feature set / strategy / timeframe. (420+ absolute-threshold
    # experiments found nothing; this encodes that lesson.)
    fail_counts: dict[tuple, int] = {}
    for r in read_log():
        st = r.get("status")
        unsuccessful = st in ("scout_failed", "failed") or (
            st == "completed"
            and (r.get("metrics", {}).get("profit_pct") or 0) <= 0
        )
        if unsuccessful:
            key = _family_key(r.get("config", {}), r.get("window", ""))
            fail_counts[key] = fail_counts.get(key, 0) + 1
    exhausted_notified: set[tuple] = set()

    queued = 0
    for v in all_variants:
        cfg = _stamp_target_version(v["config"])
        for win_name in target_windows:
            if win_name not in WINDOWS:
                continue
            if (_ch(cfg), win_name) in already_queued:
                continue  # Fix 13: skip already-queued (config, window) pairs
            fam = _family_key(cfg, win_name)
            if fail_counts.get(fam, 0) >= EXHAUSTED_FAMILY_LIMIT:
                if fam not in exhausted_notified:
                    exhausted_notified.add(fam)
                    print(f"[brain] family EXHAUSTED ({fail_counts[fam]} failures) on "
                          f"{win_name}: tf={cfg.get('timeframe')} feat={cfg.get('feature_set')} "
                          f"— refusing more param-only configs")
                    _notify_family_exhausted(cfg, win_name, fail_counts[fam])
                continue
            queue_hypothesis(
                config=cfg,
                band=v["band"],
                rationale=v["rationale"],
                window=win_name,
                timerange=WINDOWS[win_name],
                parent_id=v.get("parent_id"),
            )
            queued += 1
    return queued


if __name__ == "__main__":
    import json
    n = queue_seed_if_empty()
    if n > 0:
        print(f"Queued seed × {n} (both v22 + v23 × all windows)")
    else:
        added = generate_and_queue(safe_n=4, aggressive_n=6, windows=["bull_2024Q1", "bear_2025Q1"])
        print(f"Queued {added} new hypotheses")
