"""initial platform schema

Revision ID: 0001
Revises:
Create Date: 2026-07-17

Hand-written (not autogenerated) so it can be authored before the target
database exists — see scripts/platform/bootstrap_db.sql for the one-time
superuser step this depends on. Mirrors schema.py exactly; once the DB is
live, `alembic revision --autogenerate` should show zero diff against this.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.String, primary_key=True),
        sa.Column("email", sa.String, nullable=False, unique=True),
        sa.Column("is_admin", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("trading_enabled", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("status", sa.String, nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.String, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("stripe_customer_id", sa.String, nullable=True),
        sa.Column("stripe_subscription_id", sa.String, nullable=True, unique=True),
        sa.Column("plan", sa.String, nullable=True),
        sa.Column("status", sa.String, nullable=False, server_default="incomplete"),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_subscriptions_user_id", "subscriptions", ["user_id"])

    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.String, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("exchange", sa.String, nullable=False),
        sa.Column("label", sa.String, nullable=True),
        sa.Column("ciphertext", sa.LargeBinary, nullable=False),
        sa.Column("nonce", sa.LargeBinary, nullable=False),
        sa.Column("wrapped_dek", sa.LargeBinary, nullable=False),
        sa.Column("permissions_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("permissions_ok", sa.Boolean, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_api_keys_user_id", "api_keys", ["user_id"])

    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.String, sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("capital_usd", sa.Numeric, nullable=False, server_default="0"),
        sa.Column("max_risk_per_trade_pct", sa.Numeric, nullable=False, server_default="0.02"),
        sa.Column("min_confidence_threshold", sa.Numeric, nullable=False, server_default="0.60"),
        sa.Column("paper_trading", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("blocked_regimes", JSONB, nullable=False, server_default='["CRASH"]'),
        sa.Column("pairs", JSONB, nullable=False, server_default="[]"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    op.create_table(
        "execution_jobs",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.String, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("signal_id", sa.String, nullable=False),
        sa.Column("status", sa.String, nullable=False, server_default="queued"),
        sa.Column("payload", JSONB, nullable=False),
        sa.Column("result", JSONB, nullable=True),
        sa.Column("error", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_execution_jobs_status_created", "execution_jobs", ["status", "created_at"])
    op.create_index("ix_execution_jobs_user_id", "execution_jobs", ["user_id"])

    op.create_table(
        "trades",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.String, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("execution_job_id", sa.Integer, sa.ForeignKey("execution_jobs.id", ondelete="SET NULL"), nullable=True),
        sa.Column("pair", sa.String, nullable=False),
        sa.Column("side", sa.String, nullable=False),
        sa.Column("entry_price", sa.Numeric, nullable=False),
        sa.Column("exit_price", sa.Numeric, nullable=True),
        sa.Column("size", sa.Numeric, nullable=False),
        sa.Column("pnl", sa.Numeric, nullable=True),
        sa.Column("status", sa.String, nullable=False, server_default="open"),
        sa.Column("paper", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("strategy_id", sa.String, nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", JSONB, nullable=True),
    )
    op.create_index("ix_trades_user_id", "trades", ["user_id"])
    op.create_index("ix_trades_user_status", "trades", ["user_id", "status"])

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.String, sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("actor", sa.String, nullable=False),
        sa.Column("action", sa.String, nullable=False),
        sa.Column("detail", JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_audit_log_user_id", "audit_log", ["user_id"])
    op.create_index("ix_audit_log_created_at", "audit_log", ["created_at"])

    op.create_table(
        "seen_signals",
        sa.Column("signal_id", sa.String, primary_key=True),
        sa.Column("user_id", sa.String, sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    op.create_table(
        "seen_stripe_events",
        sa.Column("event_id", sa.String, primary_key=True),
        sa.Column("event_type", sa.String, nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table("seen_stripe_events")
    op.drop_table("seen_signals")
    op.drop_index("ix_audit_log_created_at", table_name="audit_log")
    op.drop_index("ix_audit_log_user_id", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("ix_trades_user_status", table_name="trades")
    op.drop_index("ix_trades_user_id", table_name="trades")
    op.drop_table("trades")
    op.drop_index("ix_execution_jobs_user_id", table_name="execution_jobs")
    op.drop_index("ix_execution_jobs_status_created", table_name="execution_jobs")
    op.drop_table("execution_jobs")
    op.drop_table("user_settings")
    op.drop_index("ix_api_keys_user_id", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index("ix_subscriptions_user_id", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_table("users")
