"""Auto-generate the Third-Party Integrations page by scanning source for
known external-service usage patterns.

Detects: exchange access (ccxt / Binance REST), Telegram Bot API, every LLM
provider this project has ever wired in, and a few infra dependencies
(FreqTrade/FreqAI itself, Cloudflare/nginx references in comments). Each
hit is grouped by service with every file that touches it, so this page
also functions as a live "what would break if this API key rotated / this
service went down" map -- built from the code, not from memory of what was
wired in eight months ago.

Runs as a `mkdocs-gen-files` plugin, same mechanism as gen_ref_pages.py.
"""
from __future__ import annotations

import re
from pathlib import Path

import mkdocs_gen_files

ROOT = Path(__file__).resolve().parent.parent

SCAN_ROOTS = [
    "scripts", "dashboard",
    "freqtrade/user_data/strategies", "freqtrade/user_data/scripts",
    "freqtrade/user_data/freqaimodels",
]
SKIP_DIR_NAMES = {"__pycache__", "node_modules"}

# service_label -> list of (compiled_regex, human note)
SERVICES: dict[str, list[tuple[re.Pattern, str]]] = {
    "Binance (exchange, live trading + market data)": [
        (re.compile(r"\bimport ccxt\b"), "ccxt exchange client"),
        (re.compile(r"binance\.com|fapi\.binance\.com"), "direct Binance REST call"),
        (re.compile(r"FREQTRADE__EXCHANGE__KEY|FREQTRADE__EXCHANGE__SECRET"), "exchange credentials"),
    ],
    "Other exchanges (arbitrage price feeds only, paper)": [
        (re.compile(r"\bbybit\b|\bhtx\b|\bbitfinex\b|\bokx\b", re.I), "ccxt exchange id referenced"),
    ],
    "Telegram Bot API": [
        (re.compile(r"api\.telegram\.org"), "direct Telegram Bot API call"),
        (re.compile(r"TELEGRAM_TOKEN|FREQTRADE__TELEGRAM__TOKEN|BRAIN_TELEGRAM_TOKEN"), "bot token env var"),
    ],
    "Anthropic (Claude)": [
        (re.compile(r"\banthropic\b", re.I), "Anthropic SDK/API reference"),
        (re.compile(r"ANTHROPIC_API_KEY"), "credential env var"),
    ],
    "xAI (Grok)": [
        (re.compile(r"\bgrok\b|\bxai\b", re.I), "xAI/Grok reference"),
        (re.compile(r"XAI_API_KEY"), "credential env var"),
    ],
    "Google (Gemini)": [
        (re.compile(r"\bgemini\b", re.I), "Gemini reference"),
        (re.compile(r"GEMINI_API_KEY"), "credential env var"),
    ],
    "DeepSeek": [
        (re.compile(r"\bdeepseek\b", re.I), "DeepSeek reference"),
        (re.compile(r"DEEPSEEK_API_KEY"), "credential env var"),
    ],
    "FreqTrade / FreqAI (core trading framework)": [
        (re.compile(r"^\s*from freqtrade[.\w]* import|^\s*import freqtrade\b"), "freqtrade import"),
    ],
    "External market/sentiment data (Phase 2 fetchers)": [
        (re.compile(r"alternative\.me|coingecko|cryptopanic|defillama|trends\.google", re.I), "external data source"),
    ],
}


def _scan_file(path: Path) -> dict[str, list[str]]:
    """Return {service_label: [note, ...]} for hits in this one file."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return {}
    hits: dict[str, list[str]] = {}
    for service, patterns in SERVICES.items():
        for regex, note in patterns:
            if regex.search(text):
                hits.setdefault(service, [])
                if note not in hits[service]:
                    hits[service].append(note)
    return hits


def main() -> None:
    by_service: dict[str, dict[str, list[str]]] = {s: {} for s in SERVICES}
    for root_str in SCAN_ROOTS:
        root = ROOT / root_str
        if not root.exists():
            continue
        for py_file in sorted(root.rglob("*.py")):
            if any(part in SKIP_DIR_NAMES for part in py_file.parts):
                continue
            hits = _scan_file(py_file)
            rel = py_file.relative_to(ROOT).as_posix()
            for service, notes in hits.items():
                by_service[service][rel] = notes

    lines = [
        "# Third-Party Integrations\n\n",
        "Generated by scanning every script under `scripts/`, `dashboard/`, "
        "and the FreqTrade user_data tree for known usage patterns -- this "
        "is a live map of external dependencies, not a hand-maintained list "
        "that goes stale the moment an integration is added or dropped. See "
        "also `CLAUDE.md`'s \"Models That Were Dropped and Why\" for "
        "integrations that were intentionally retired.\n\n",
    ]
    for service, files in by_service.items():
        if not files:
            continue
        lines.append(f"## {service}\n\n")
        lines.append(f"**{len(files)} file(s)** reference this integration.\n\n")
        lines.append("| File | Detected |\n|---|---|\n")
        for rel, notes in sorted(files.items()):
            lines.append(f"| `{rel}` | {', '.join(notes)} |\n")
        lines.append("\n")

    with mkdocs_gen_files.open("third-party.md", "w") as f:
        f.writelines(lines)


main()
